"""
dialogs/weight_sensor.py
────────────────────────
Diagnostic dialog for the HX711 load-cell amplifier.
"""

import os
import json
import time
import random
import statistics

from PyQt6.QtWidgets import (
    QDialog, QLabel, QPushButton,
    QVBoxLayout, QHBoxLayout, QMessageBox,
)
from PyQt6.QtCore import Qt, QTimer

from utils import screen_size

# Assumes this dialog is in a folder (e.g. /dialogs/) next to /hardware/
CALIB_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "hardware", "weight_calibration.json")


class WeightSensorTestDialog(QDialog):
    """Diagnostic dialog for the HX711 load-cell amplifier."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Weight Sensor Test")
        self.showFullScreen()
        self.setStyleSheet("background-color: #ECEFF1;")

        SW, _ = screen_size()
        scale  = SW / 800
        fs     = max(13, int(18 * scale))
        fs_big = max(30, int(60 * scale))
        btn_h  = max(50, int(70 * scale))

        self.MOCK_HARDWARE = True
        self.mock_weight   = 0.00
        self.calib         = {"offset": 0, "units_per_kg": 1.0}
        self.hx            = None

        self._init_hx711()
        self._build_ui(scale, fs, fs_big, btn_h)

        # Timer for continuous reading
        self.timer = QTimer(self)
        self.timer.timeout.connect(self._update_weight_reading)
        self.timer.start(400)  # slightly faster for responsiveness

    # ── Hardware init ────────────────────────────────────────────────────────

    def _init_hx711(self):
        try:
            import RPi.GPIO as GPIO  # type: ignore
            from hx711 import HX711  # type: ignore

            GPIO.setmode(GPIO.BCM)
            self.hx = HX711(dout_pin=5, pd_sck_pin=6)
            self.hx.reset()

            # Load calibration data generated by hardware/test_weight.py
            if os.path.exists(CALIB_FILE):
                with open(CALIB_FILE, "r") as f:
                    data = json.load(f)
                    if "offset" in data and "units_per_kg" in data:
                        self.calib = data
                        print(f"[HX711] Loaded calibration: {self.calib}")
            else:
                print("[HX711] Warning: weight_calibration.json not found.")

            self.MOCK_HARDWARE = False

        except ImportError:
            print("[HX711] Libraries missing. Running in MOCK mode.")
            self.MOCK_HARDWARE = True
        except Exception as e:
            print(f"[HX711] Setup failed: {e}. Running in MOCK mode.")
            self.MOCK_HARDWARE = True

    # ── Sensor Reading Logic (Matches test_weight.py) ─────────────────────────

    def _get_raw_median(self, times: int = 5) -> float | None:
        """Gets raw ADC data and applies median filter to ignore OS spikes."""
        if not self.hx:
            return None
        try:
            data = self.hx.get_raw_data(times=times)
            if data and len(data) >= 3:
                return statistics.median(data)
            elif data and len(data) > 0:
                return sum(data) / len(data)
        except Exception:
            pass
        return None

    # ── UI ───────────────────────────────────────────────────────────────────

    def _build_ui(self, scale: float, fs: int, fs_big: int, btn_h: int):
        main_layout = QVBoxLayout()
        main_layout.setAlignment(Qt.AlignmentFlag.AlignCenter)
        main_layout.setSpacing(int(10 * scale))
        main_layout.setContentsMargins(20, 10, 20, 10)

        title = QLabel("Load Cell & HX711 Diagnostics")
        title.setStyleSheet(
            f"font-size: {max(16, int(22*scale))}px; font-weight: bold; color: #333;"
        )
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        main_layout.addWidget(title)
        
        mode_str = "HARDWARE MODE" if not self.MOCK_HARDWARE else "MOCK MODE"
        mode_color = "#4CAF50" if not self.MOCK_HARDWARE else "#FF9800"
        mode_lbl = QLabel(f"● {mode_str}")
        mode_lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
        mode_lbl.setStyleSheet(f"font-size: {fs}px; font-weight: bold; color: {mode_color};")
        main_layout.addWidget(mode_lbl)

        # Main Weight Display
        self.reading_label = QLabel("0.000 kg")
        self.reading_label.setStyleSheet(
            f"font-size: {fs_big}px; font-weight: bold; color: #1565C0; "
            f"background-color: white; border: 4px solid #ccc; "
            f"border-radius: 12px; padding: 10px;"
        )
        self.reading_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        main_layout.addWidget(self.reading_label)

        # Raw ADC Display (Very helpful for debugging hardware)
        self.raw_label = QLabel("Raw ADC: —")
        self.raw_label.setStyleSheet(f"font-size: {fs}px; color: #757575;")
        self.raw_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        main_layout.addWidget(self.raw_label)

        main_layout.addLayout(self._action_buttons(fs, btn_h))

        exit_btn = QPushButton("Exit Hardware Test")
        exit_btn.setMinimumHeight(btn_h)
        exit_btn.setStyleSheet(
            f"font-size: {fs}px; font-weight: bold; "
            f"background-color: #9e9e9e; color: white; border-radius: 8px;"
        )
        exit_btn.clicked.connect(self.accept)
        main_layout.addWidget(exit_btn)

        self.setLayout(main_layout)

    def _action_buttons(self, fs: int, btn_h: int) -> QHBoxLayout:
        row = QHBoxLayout()

        tare_btn = QPushButton("Tare (Zero Scale)")
        tare_btn.setMinimumHeight(btn_h)
        tare_btn.setStyleSheet(
            f"font-size: {fs}px; font-weight: bold; "
            f"background-color: #FF9800; color: white; border-radius: 8px;"
        )
        tare_btn.clicked.connect(self._tare_scale)
        row.addWidget(tare_btn)

        if self.MOCK_HARDWARE:
            sim_btn = QPushButton("Simulate +100g")
            sim_btn.setMinimumHeight(btn_h)
            sim_btn.setStyleSheet(
                f"font-size: {fs}px; font-weight: bold; "
                f"background-color: #4CAF50; color: white; border-radius: 8px;"
            )
            sim_btn.clicked.connect(self._simulate_weight)
            row.addWidget(sim_btn)

        return row

    # ── Callbacks ────────────────────────────────────────────────────────────

    def _update_weight_reading(self):
        if self.MOCK_HARDWARE:
            display = self.mock_weight + random.uniform(-0.002, 0.002)
            self.reading_label.setText(f"{display:.3f} kg")
            self.raw_label.setText("Raw ADC: (Mocked)")
        else:
            raw = self._get_raw_median(times=5)
            if raw is not None:
                kg = (raw - self.calib["offset"]) / self.calib["units_per_kg"]
                self.reading_label.setText(f"{kg:.3f} kg")
                self.raw_label.setText(f"Raw ADC: {raw:.0f}")
            else:
                self.reading_label.setText("Error Reading")
                self.raw_label.setText("Raw ADC: —")

    def _tare_scale(self):
        if self.MOCK_HARDWARE:
            self.mock_weight = 0.00
            self.reading_label.setText("0.000 kg")
        else:
            self.reading_label.setText("Taring...")
            self.raw_label.setText("Taking samples...")
            # Use singleShot to let the UI update before the blocking read loop
            QTimer.singleShot(100, self._perform_tare_loop)

    def _perform_tare_loop(self):
        """Takes multiple readings to set a new zero offset, saves to JSON."""
        samples = []
        for _ in range(10):
            val = self._get_raw_median(times=5)
            if val is not None:
                samples.append(val)
            time.sleep(0.05)

        if samples:
            new_offset = sum(samples) / len(samples)
            self.calib["offset"] = new_offset
            
            # Save the new offset back to the file so it persists
            try:
                # Ensure directory exists just in case
                os.makedirs(os.path.dirname(CALIB_FILE), exist_ok=True)
                with open(CALIB_FILE, "w") as f:
                    json.dump(self.calib, f, indent=2)
                print(f"[HX711] New tare offset saved: {new_offset:.0f}")
            except Exception as e:
                print(f"[HX711] Error saving calibration: {e}")
                
        else:
            QMessageBox.warning(self, "Tare Failed", "Could not read from sensor.")

    def _simulate_weight(self):
        self.mock_weight += 0.100

    # ── Cleanup ──────────────────────────────────────────────────────────────

    def accept(self):
        self.timer.stop()
        if not self.MOCK_HARDWARE and self.hx:
            try:
                self.hx.power_down()
            except Exception:
                pass
        super().accept()